### ISSUE TITLE
Toml config files cannot have sections

### ISSUE THREAD

**Issue by julesbertrand** [artefactory/vertex-pipelines-deployer#119]
## 🐛 Bug Report

As config files are enforced to be flat (with all parameters at the root of the config), it is not possible to have multiple sections in a toml config file for vertex-deployer. A desired behavior would be to have sections that are flattened y default or to be able to give a toml parser in a python file to do so.

### Code sample

today: 

```toml
# modeling
verbosity = -1
boosting_type = "gbdt"
random_state = 42
max_depth = 5
n_estimators = 100
objective = "rmse"
```

expected:

```toml
[parameter_values.modeling]
verbosity = -1
boosting_type = "gbdt"
random_state = 42
max_depth = 5
n_estimators = 100
objective = "rmse"
```
gives dict:
```python
{
    "modeling_verbosity": -1,
    "modeling_boosting_type": "gbdt",
    "modeling_random_state": 42,
    "modeling_max_depth": 5,
    "modeling_n_estimators": 100,
    "modeling_objective": "rmse",
}
```

### Environment

* OS: [e.g. Linux / Windows / macOS]
* Python version, get it with: 3.10

## 📈 Expected behavior

Be able to have sections in toml config files, as it is why we want to use them.
