### ISSUE TITLE
Configurations not taken into account when set in pyproject.toml

### ISSUE THREAD

**Issue by sebvln** [artefactory/vertex-pipelines-deployer#220]
## 🐛 Bug Report

Settings vertex-deployer global configurations in pyproject.toml doesn't work.

## 🔬 How To Reproduce

1. Check your configs:
    > ```bash vertex-deployer config --all```
2. Update some configurations in pyproject.toml
```toml
[tool.vertex-deployer]
vertex_folder_path = "some_new_default_path"
log_level = "some_new_log_level"

[tool.vertex-deployer.deploy]
scheduler_timezone = "Another/Timezone"
```
3. Check your configs again
    > ```bash vertex-deployer config --all```

### Environment

* OS: macOS
* Python version: 3.11.9
